Please do not merge GUVNOR-3193 Change Project from a folder in a repo to a repository
uberfire/uberfire pull request #814
Opened 2017-08-29 10:29 UTC by Rikkola

Please do not merge.
Also no need for review, yet.

Just using the build servers to run the tests since they take few hours locally.

https://issues.jboss.org/browse/GUVNOR-3193

The related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/496
- https://github.com/kiegroup/drools/pull/1402
- https://github.com/kiegroup/guvnor/pull/487
- https://github.com/kiegroup/kie-wb-common/pull/1015
- https://github.com/kiegroup/drools-wb/pull/566
- https://github.com/kiegroup/jbpm-designer/pull/643
- https://github.com/kiegroup/jbpm-wb/pull/832
- https://github.com/kiegroup/kie-wb-distributions/pull/573

2017-11-01 16:33 UTC, Rikkola commented on uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/repositories/RepositoryCopierImplTest.java
> +    public void noBranch() throws Exception {
Could use some help here. Trying to set a test up that verifier the content actually moves from A to B, but I keep getting an exception about conflicting file name.

2017-11-02 12:49 UTC, jhrcek reviewed
Few comments inline..

2017-11-02 12:49 UTC, jhrcek commented on uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/impl/git/GitRepository.java
> +        if (branches.containsKey(branchName)) {
You can avoid if-else by just using `Optional.ofNullable(branches.get(branchName))`

2017-11-02 12:49 UTC, jhrcek commented on uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryCopierImpl.java
> +             targetRepository.getDefaultBranch().get().getPath());
Calling get() on optional without isPresent check.. can you guarantee that getDefaultBranch() always returns non-empty Optional?

2017-11-02 12:49 UTC, jhrcek commented on uberfire-structure/uberfire-structure-client/src/main/java/org/guvnor/structure/client/editors/context/GuvnorStructureContext.java
> +                            repository.getDefaultBranch().get().getName());
optional.get() without isPresent check - 4 times in this file

2017-11-02 12:49 UTC, jhrcek commented on uberfire-structure/uberfire-structure-client/src/main/java/org/guvnor/structure/client/editors/fileexplorer/FileExplorerViewImpl.java
> +        final Optional<Branch> branchOptional = repository.getBranch(branch);
More idiomatic (hopefuly not idiotic :) Java 8 way:

```
repository.getBranch(branchName).ifPresent(
         branch -> do what you want with branch
);
```

2017-11-02 12:59 UTC, Rikkola commented on uberfire-project/uberfire-project-client/src/main/java/org/guvnor/common/services/project/client/preferences/ProjectScopedResolutionStrategySupplier.java
> +    public void selectedProjectChanged( @Observes final ProjectContextChangeEvent event ) {
Possible. I started ages ago. Now now, what would be the fastest way to reformat everything.

2017-11-06 07:03 UTC, Rikkola commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestHelper.java
> +                || !("clone".equals(repository.getRequestType()))) {
True

2017-11-06 07:11 UTC, Rikkola commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
> +            throw new WebApplicationException(Response.status(Response.Status.NOT_FOUND).entity(organizationalUnit).build());
Yes. Should use the name.

And below I should actually use the ou to fetch the projects. Currently I just fetched all of them.

2017-11-06 07:13 UTC, Rikkola commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
> +        final ProjectResponse projectReq = new ProjectResponse();
Renamed to `projectResponse`, I prefer long variables.

2017-11-06 07:32 UTC, Rikkola commented on uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/Branch.java
> +    private Path path;
It is like GIT. The thing is, you can't really use a path to point to a repository. Just to a branch and then a repository is a set of branches. If the repository has no branches it has no path that we can use to point to it. The UI can't actually handle repositories like that now.

This is something that we kept doing in our code `repository.getRootPath()` and that gives the Path for master branch, but even with our own deprecated asset-mgmt codes we did not use master. The repository might not even have a master branch. So what is the repository root then?

This is something I wanted to fix to some extent during these changes. The changes still have the default root for repository, that is master if master exists.

In the Project class the project root is this branch Path. The Project class does have the Repository, but since it does not have a currently active branch variable, we can not use it. Not that is should be used. Repository just represents the git-repository as it is. Project class on the other hand is not GIT or Maven project, but a workbench project. If things get crazy we can swap GIT to CVS and Maven to Gradle, but the Project remains.

2017-11-06 07:33 UTC, Rikkola commented on uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/repositories/Branch.java
> +    private Path path;
At some point it might be best to remove Repository and OrganizationalUnit from the Project class. I feel there might be a window for bugs here if the repository is renames or project moved to another OU. But took the short route here for now, just to get things working.

2017-11-06 07:36 UTC, Rikkola commented on uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/repositories/RepositoryCopierImpl.java
> +             targetRepository.getDefaultBranch().get().getPath());
I like living on the edge.



Not really, changing it.

2017-11-06 07:46 UTC, Rikkola commented on uberfire-structure/uberfire-structure-client/src/main/java/org/guvnor/structure/client/editors/context/GuvnorStructureContext.java
> +                            repository.getDefaultBranch().get().getName());
Yeah if there is no default branch then the Workbench is broken anyway, but best to prepare for future. We used to assume master exists and now it is hard to know what breaks if it does not. Fixing these.

2017-11-15 12:30 UTC, jakubschwan reviewed
I added some comments to a REST part of this PR

2017-11-15 12:55 UTC, ederign requested changes
Tony, overall looks good, but before doing a more detailed review I have one first question:

Please correct me if I'm wrong ok?

In the new structure:

I have a space 

A module is a folder that contains a pom.xml

In the physical world:
Each repo will have at least 1 module and 1 module can have n child modules.
i.e. module root + childs (api, backend and client)

A project is an abstract concept, it doesn't exist as something physical, just as a concept. In the abstract world:

Each repo will have at least 1 project and this project can 1..n module and 1 module can have 1..n child modules.
i.e. module root + childs (api, backend and client)

Is that right?

If that is the case, here are my comments:

"the new Project is the active project that the workbench is presenting in the UI or the Project that we can later build ( these changes still only support building single Modules ). The Project has an active branch and branch changes require a recreation of the Project ( We can change this later, but after spending months with the code it is quite clear that keeping this step will save us from an extra month of code changes and bug fixes. )"


For me this project nomenclature that you use is misleading. We mix 'Project' abstract concept  with something that could be better called like Workspace because it tracks the active project working  + active branch + any specific configuration of the workbench+user for that open project.

wdyt?

2017-11-15 13:03 UTC, Rikkola commented on uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/Project.java
> + * Please do not use the Repository root path, this can point to any branch even to those that are not used.
Really good point. This way it is protected. And I assume you meant the real repository. So if repository root is called exception is thrown.

2017-11-15 13:04 UTC, Rikkola commented on uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/Project.java
> + * Please do not use the Repository root path, this can point to any branch even to those that are not used.
Although, we should also remove the getRepositoryRoot() method all together from Repository. All it will ever give us is trouble.

2017-11-15 13:33 UTC, Rikkola commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestScheduler.java
>      public void installProjectRequest(final InstallProjectRequest jobRequest) {
Yes I think it should. Previously the repository could just be cloned in without belonging into an organizational unit, but now we require this. So if you now install using this method as it is, you have a repository that you can't later add to an OU.

2017-11-15 13:38 UTC, Rikkola commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
> +    @Path("/projects/{projectName}/maven/test")
This is the correct way.

2017-11-15 13:39 UTC, Rikkola commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
>      public Response removeRepositoryFromOrganizationalUnit(@PathParam("organizationalUnitName") String organizationalUnitName,
Due to the fact that each project can now only belong into one OU. This method now needs to be deleted. Still thank you for pointing it out.

2017-11-15 13:58 UTC, jakubschwan commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/JobRequestHelper.java
> +    public JobResult cloneRepository(final String jobId,
If I clone a git repository, then result of this operation should be a new project, right?

2017-11-23 19:21 UTC, ederign requested changes
@Rikkola can you please take a look on this?

2017-11-23 19:21 UTC, ederign commented on uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/WorkspaceProject.java
> +    private Repository repository;
did u create the wrapper for throw a error when getRoopath is called?

2017-11-23 19:21 UTC, ederign commented on uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/WorkspaceProject.java
> +        return repository;
please add the wrapper.

2017-11-23 19:21 UTC, ederign commented on uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/project/ProjectMigrationService.java
> +public interface ProjectMigrationService {
Workspace?

2017-11-23 19:21 UTC, ederign commented on uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/ProjectSearchService.java
>  public interface ProjectSearchService {
workbench?

2017-11-23 19:21 UTC, ederign commented on uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/ProjectService.java
> +public interface ProjectService {
workbench?

2017-11-23 19:21 UTC, ederign commented on uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/service/ProjectService.java
> +public interface ProjectService {
s/workbench/workspace

2017-11-23 19:21 UTC, ederign commented on uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ProjectMigrationServiceImpl.java
> +    public ProjectMigrationServiceImpl() {
Workspace?

2017-11-23 19:21 UTC, ederign commented on uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ProjectSearchServiceImpl.java
> +    public ProjectSearchServiceImpl(final ProjectService projectService) {
WorkspaceProject

2017-11-23 19:21 UTC, ederign commented on uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ProjectServiceImpl.java
> +public class ProjectServiceImpl
Workspace

2017-11-23 19:21 UTC, ederign commented on uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/ProjectServiceImpl.java
> +    public Collection<WorkspaceProject> getAllProjects() {
getAllWorskpaces

2017-11-23 19:21 UTC, ederign commented on uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/social/NewProjectEventAdapter.java
> +public class NewProjectEventAdapter implements SocialAdapter<NewModuleEvent> {
NewModule ?

2017-11-23 19:22 UTC, ederign commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
>      public Response removeRepositoryFromOrganizationalUnit(@PathParam("organizationalUnitName") String organizationalUnitName,
workspaceprojects or modules?

2017-11-23 19:22 UTC, ederign commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
>      public Response addRepositoryToOrganizationalUnit(@PathParam("organizationalUnitName") String organizationalUnitName,
workspace project or modules?

2017-11-23 19:23 UTC, ederign commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
> +    @Path("/projects/{projectName}/maven/test")
workspaceprojects or modules?

2017-11-24 07:40 UTC, Rikkola commented on uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/context/ProjectContext.java
>  public class ProjectContext {
Makes sense. I'll change that.

2017-11-24 07:41 UTC, Rikkola commented on uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/ProjectWizard.java
> +    void start(final Callback<WorkspaceProject> callback,
I guess we can rename this too. Just to avoid confusion with the different project types (Maven, GIT, workbench).

2017-11-24 07:41 UTC, Rikkola commented on uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/WorkspaceProject.java
> +    private Repository repository;
I removed the root path. This takes care of the problem and removes the, well, root path. Since there is no real root.

2017-11-24 07:44 UTC, Rikkola commented on uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/social/NewProjectEventAdapter.java
> +public class NewProjectEventAdapter implements SocialAdapter<NewModuleEvent> {
This, I need to take a closer look at. Not sure if this should track project or module.

2017-11-24 09:21 UTC, Rikkola commented on uberfire-rest/uberfire-rest-backend/src/main/java/org/guvnor/rest/backend/ProjectResource.java
> +    @Path("/projects/{projectName}/maven/test")
This builds the full Project. We can rename this too.

2017-11-29 11:47 UTC, ederign commented
Can you please move this PR for https://github.com/kiegroup/appformer ?

2018-05-07 07:16 UTC, closed without merging