Fix Windows specific issues
uberfire/uberfire pull request #878
Opened 2017-10-18 11:30 UTC by mackaypeter

Fixing some of the Windows specific issues.

2017-10-18 11:33 UTC, jomarko reviewed
One minor comment form my site, but sure, thanks for the PR.

2017-10-18 11:33 UTC, jomarko commented on uberfire-nio2-backport/uberfire-nio2-api/src/test/java/org/uberfire/java/nio/file/PathsTest.java
> -        assertThat(path.toString()).isEqualTo("c:\\path" + separator() + "to" + separator() + "file.txt");
Please remove the method separator() that is now unused I think.

2017-10-18 13:53 UTC, baldimir requested changes
Please see Jozef's comment, otherwise, looks ok.

2017-10-18 16:06 UTC, mackaypeter commented on uberfire-nio2-backport/uberfire-nio2-api/src/test/java/org/uberfire/java/nio/file/PathsTest.java
> -        assertThat(path.toString()).isEqualTo("c:\\path" + separator() + "to" + separator() + "file.txt");
Right, thanks for catching it.

2017-10-18 16:07 UTC, mackaypeter commented
Thanks for the reviews, I removed the redundant separator() method.

2017-10-18 17:05 UTC, jomarko approved these changes
thanks

2017-10-19 07:03 UTC, baldimir approved these changes

2017-10-19 12:50 UTC, ederign requested changes
Hi @mackaypeter thanks for your PR. 

It's really important for us to fix path on Windows FS. But I would like to ask you to add test coverage to your PR especially with examples of the critical paths.

2017-10-19 12:51 UTC, ederign requested changes

2017-10-19 12:51 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-fs/src/main/java/org/uberfire/java/nio/fs/file/BaseSimpleFileSystem.java
> +    public String getSeparator(final String path) {
Please add test coverage

2017-10-19 12:51 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-fs/src/main/java/org/uberfire/java/nio/fs/file/BaseSimpleFileSystem.java
> +        if (path.equals("/")) {
Please add test coverage

2017-10-19 12:51 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> +        if (other.isAbsolute() != isAbsolute()) {
Please add test coverage

2017-10-19 12:51 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> +        while (thatPosition > 0) {
Please add test coverage

2017-10-19 12:51 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> +    private List<String> getNamesIncludingRoot() {
Please add test coverage to all methods above

2017-10-24 15:30 UTC, mackaypeter commented
Hi @ederign,
thanks for the feedback, I updated the PR.

2017-10-26 11:46 UTC, ederign requested changes

2017-10-26 11:46 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> -        if (that.path.length > path.length) {
Why did you remove this check?

2017-10-26 11:46 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> +        if (other.isAbsolute() != isAbsolute()) {
Why did you change the order of instanceOf AbstractPath? Are you sure that this doesn't break with other implementations of Path? Like (JGitFSPath)

2017-10-26 11:46 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> -        for (int i = 0; i < thatOffsetCount; i++) {
Why did you remove this check?

2017-10-26 11:46 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> -        while (i < that.path.length) {
Why did you remove this check?

2017-10-26 11:46 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> -        if (i < path.length && this.path[i] != fs.getSeparator().charAt(0)) {
Why did you remove this check?

2017-10-26 11:46 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> -        if (thatOffsetCount > thisOffsetCount) {
Why did you remove this check?

2017-10-26 11:46 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> -        if (this.equals(other)) {
Why did you remove this check?

2017-10-26 11:46 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> +        return '/';
Why did you for the separator has / here?

2017-10-26 11:46 UTC, ederign commented on uberfire-nio2-backport/uberfire-nio2-model/src/test/java/org/uberfire/java/nio/base/GeneralPathTest.java
> +                                   "c:\\path\\to\\some\\place",
This test isn't to test unix paths?

2017-10-27 08:44 UTC, mackaypeter commented on uberfire-nio2-backport/uberfire-nio2-model/src/test/java/org/uberfire/java/nio/base/GeneralPathTest.java
> +                                   "c:\\path\\to\\some\\place",
It's the `testRelativizeWindows()` test.

2017-10-27 08:47 UTC, mackaypeter commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> +        return '/';
Because unless the path uses windows format, then the separator will always be /.
Paths can use / as a separator even on windows for example /C:/Users, but `fs.getSeparator()` would return backslash, which was causing a lot of issues.

2017-10-27 09:56 UTC, mackaypeter commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> +        if (other.isAbsolute() != isAbsolute()) {
I'm not 100% sure I understand you correctly, but if you mean why I am doing the isAbsolute check before the instanceof, I don't think the order should matter. But I can switch them around if you'd like to.

2017-10-27 10:28 UTC, mackaypeter commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> -        for (int i = 0; i < thatOffsetCount; i++) {
In case of _/C:/Users_ vs. _C:\Users_ , this would fail, because everything is offset by 1.

2017-10-27 10:31 UTC, mackaypeter commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> -        while (i < that.path.length) {
I am now checking the path segments themselves, ignoring separators, so checking every char is redundant.

2017-10-27 11:11 UTC, mackaypeter commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> -        if (that.path.length > path.length) {
Because of issues with /C:/ vs C:\ and trailing separators. I guess it could checking length+2 would work, but removing it seemed cleaner.

2017-10-27 11:15 UTC, mackaypeter commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> -        if (i < path.length && this.path[i] != fs.getSeparator().charAt(0)) {
I am only checking the actual names in a path, ignoring separators.

2017-10-27 11:20 UTC, mackaypeter commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> -        if (this.equals(other)) {
Because, for example _C:\Users_ and _/C:/Users_ will not actually be equal as Path objects.

2017-10-27 11:29 UTC, mackaypeter commented on uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
> -        if (thatOffsetCount > thisOffsetCount) {
`thatOffsetCount > thisOffsetCount` is the same as `thatNameCount > thisNameCount`

As for the expectedLen part, due to having to consider the length differences of unix paths and windows paths using both formats, it got quite convoluted, so I ended up removing it, since it is not actually necessary.

2017-11-13 14:16 UTC, baldimir commented
@ederign could you please take a look at this?

2017-11-23 14:54 UTC, ederign commented
@baldimir  first of all sorry for the delay. But unfortunately, this will still take a while in order to review it.  The author changed a lot of files, moving/removing some pieces of code. I've to carefully look at this in order to don't break anything. Maybe @porcelli or @manstis  can take a look on this.

2017-11-27 13:58 UTC, baldimir commented
@ederign @porcelli @manstis np will delay, just want to say that merging this (if it is ok) can help us a lot, because these fixes are related to test fails on Windows environments. So if anyone else have time and could take a look now, QE will send a virtual 🍺 or 🍻  to them.

2017-11-29 11:47 UTC, ederign commented
Can you please move this PR for https://github.com/kiegroup/appformer ?

2017-11-29 13:03 UTC, mackaypeter commented
@ederign sure, done.
kiegroup/appformer#103

2019-06-03 10:51 UTC, mackaypeter commented
This was replaced by kiegroup/appformer#103 , closing.

2019-06-03 10:51 UTC, closed without merging