Guvnor 3125
uberfire/uberfire pull request #889
Opened 2017-10-26 20:08 UTC by desmax74

Classes moved from old guvnor repo plus MaxB updated by APorcelli

2017-11-13 06:42 UTC, jhrcek requested changes

2017-11-13 06:42 UTC, jhrcek commented on uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/builder/model/BuildMessage.java
> +public class BuildMessage implements Serializable, Comparable {
Please avoid using raw types. Using `Comparable<BuildMessage>` is more type safe and you can avoid casting in compareTo implementation:

```
    @Override
    public int compareTo(BuildMessage other) {
        return Comparator.comparing(BuildMessage::getText).compare(this, other);
    }
```

The same comment applies to `ValidationMessage` below

2017-11-13 06:42 UTC, jhrcek commented on uberfire-project/uberfire-project-backend/src/test/java/org/guvnor/common/services/project/backend/server/utils/ConfigurationStaticStrategy.java
> +        conf.put(ConfigurationKey.MAVEN_PLUGINS,
Could we maybe rename these enum constants to make it clear what each of them means?

MAVEN_COMPILER_PLUGIN_GROUP
MAVEN_COMPILER_PLUGIN_ARTIFACT
MAVEN_COMPILER_PLUGIN_VERSION

and similar for Takari alternative?

2017-11-13 09:45 UTC, jhrcek approved these changes
Thanks for the changes!

2017-11-15 08:40 UTC, jhrcek reviewed
I'm writing some tests to expand coverage of POMContentHandler, but there are some problems in the dependencies being added. If you could fix / answer those I'll extend the coverage..those

2017-11-15 08:40 UTC, jhrcek commented on uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/utils/POMContentHandler.java
> +            pom.getDependencies().add(getGuvDependency(conf, "org.kie", "kie-api", kieVersion, "provided"));
Is there a reason to add `org.kie:kie-api` dependency twice or did you want to add some other dependency?

2017-11-15 08:40 UTC, jhrcek commented on uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/utils/POMContentHandler.java
> +    private Dependency getDependency(Map<ConfigurationKey, String> conf, String groupID, String artifactID, String version, String scope) {
The conf Map parameter is unused in this private method. Please remove it.

2017-11-15 08:40 UTC, jhrcek commented on uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/utils/POMContentHandler.java
> +            pom.getDependencies().add(getGuvDependency(conf, "org.optaplanner", "org.optaplanner", kieVersion, "provided"));
This second optaplanner dependency looks like a mistake too. Is there any dep with
GroupId = org.optaplanner and 
ArtifactId = ord.optaplanner?

2017-11-15 09:11 UTC, desmax74 commented on uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/utils/POMContentHandler.java
> +    private Dependency getDependency(Map<ConfigurationKey, String> conf, String groupID, String artifactID, String version, String scope) {
fixed

2017-11-15 09:11 UTC, desmax74 commented on uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/utils/POMContentHandler.java
> +            pom.getDependencies().add(getGuvDependency(conf, "org.optaplanner", "org.optaplanner", kieVersion, "provided"));
fixed

2017-11-15 09:11 UTC, desmax74 commented on uberfire-project/uberfire-project-backend/src/main/java/org/guvnor/common/services/project/backend/server/utils/POMContentHandler.java
> +            pom.getDependencies().add(getGuvDependency(conf, "org.kie", "kie-api", kieVersion, "provided"));
fixed

2017-11-29 11:47 UTC, ederign commented
Can you please move this PR for https://github.com/kiegroup/appformer ?

2019-10-04 15:10 UTC, desmax74 commented
No more
relevant after two years

2019-10-04 15:10 UTC, closed without merging