[AF-1775-6.5] SSH Ciphers and MAC configured via args on startup
uberfire/uberfire pull request #933
Opened 2019-01-09 15:40 UTC by desmax74

@porcelli

2019-01-09 19:23 UTC, porcelli approved these changes

2019-01-10 08:05 UTC, desmax74 commented
@ederign  add domhanak here

2019-01-10 13:45 UTC, jhrcek requested changes
Some logging and test fixes should be done, otherwise looks ok.
But I don't have any idea how to actually test this in the running workbench. Could you share some steps to check e.g. in git daemon of the running workbench that it's actually disabled? Or add steps to the AF-1775..

2019-01-10 13:45 UTC, jhrcek commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
> +        final ConfigProperty gitSshCipersConf = config.get("org.uberfire.nio.git.ssh.cyphers", null );
let's by consistent and use either cipher or cypher everywhere. Cipher is used in method names, why not use it in property name too?

2019-01-10 13:45 UTC, jhrcek commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/daemon/ssh/GitSSHService.java
> +        LOG.info("Added Cipher {} to the git ssh configuration. ", cipher);
This `LOG.info` will be printed out even if Exception is thrown in the try block - the info log should be moved to line 218 at the end of the try block.

2019-01-10 13:45 UTC, jhrcek commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/daemon/ssh/GitSSHService.java
> +                }else{
Formatting - missing spaces before/after else

2019-01-10 13:45 UTC, jhrcek commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/daemon/ssh/GitSSHServiceTest.java
> +        assertThat(sshService.getManagedCiphers().containsAll(ciphersReaded));
This assert does nothing - you must move the `)` to fix that. The same for assert on lines 294, 326, 329, and many others (ctrl+f `containsAll`)
```
assertThat(sshService.getManagedCiphers().containsAll(ciphersReaded));
->
assertThat(sshService.getManagedCiphers()).contains(ciphersReaded));
```

2019-01-10 13:58 UTC, jhrcek commented
@desmax74 could you please address those comments on appformer/master too, so I don't have to duplicate them?

2019-01-10 14:00 UTC, desmax74 commented
@jhrcek sure I'll apply on the master too

2019-01-10 14:17 UTC, desmax74 commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/daemon/ssh/GitSSHServiceTest.java
> +        assertThat(sshService.getManagedCiphers().containsAll(ciphersReaded));
```
assertThat(sshService.getManagedCiphers().containsAll(ciphersReaded));
->
assertThat(sshService.getManagedCiphers()).containsAll(ciphersReaded));
```

2019-01-10 14:19 UTC, desmax74 commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/daemon/ssh/GitSSHService.java
> +                }else{
Fixed

2019-01-10 14:19 UTC, desmax74 commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/daemon/ssh/GitSSHService.java
> +        LOG.info("Added Cipher {} to the git ssh configuration. ", cipher);
Fixed

2019-01-10 14:20 UTC, desmax74 commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
> +        final ConfigProperty gitSshCipersConf = config.get("org.uberfire.nio.git.ssh.cyphers", null );
Fixed

2019-01-10 14:20 UTC, desmax74 commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/daemon/ssh/GitSSHServiceTest.java
> +        assertThat(sshService.getManagedCiphers().containsAll(ciphersReaded));
Fixed

2019-01-10 14:33 UTC, jhrcek commented on uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
> +        final ConfigProperty gitSshCiphersConf = config.get("org.uberfire.nio.git.ssh.ciphers", null );
I actually meant the name of the system property should be changed to `org.uberfire.nio.git.ssh.ciphers`, but leaving the decision up to you.

2019-01-11 08:59 UTC, jhrcek approved these changes
Looks good to me. Thanks!

2019-01-11 11:32 UTC, merged